### PR TITLE
Swap behaviors

### PR DESCRIPTION
**Pull request by iwburns**
Still work to do here.  Just setting this up.

### CODE REVIEW

**Comment by iwburns** [comment]
This is failing right now because I haven't actually written the code for the new behaviors yet, but I've already written the tests for one of them.

**Comment by iwburns** [comment]
@Drakulix I put diagrams in the behavior tests this time (probably should have been doing this to begin with).  Do you mind taking a look at the behaviors that I have described there and letting me know what you think?

This PR is still breaking because I haven't started on the implementations yet, but I wanted to get your opinion on the behaviors before I did that just in case I'm not thinking about it correctly.  Thanks!  And no rush!

**Comment by iwburns** [comment]
@Drakulix I've gone back and forth with this one for a bit now and I think I'm done with it.  Would you mind taking a look at this when you get a chance?  No worries if you don't have time, just let me know.

I'd like another set of eyes on these changes, but it's not the end of the world if you don't have time for this right now.

**Comment by Drakulix** [comment]
That took some time to get through all of this, but it looks really good and with the new tests I am certain you checked every edge-case. So good to merge in my eyes!

(Sorry it took me so long to find some time)

**Comment by iwburns** [comment]
No worries at all!  I appreciate you taking a look.  I'm going to take another look at this sometime today (it's been a while since I've looked at it too) just to refresh my memory and then I'll get merging!

**Comment by Drakulix** [comment]
Is this btw the last blocker for the 1.0 release?

I would like to switch to the new API rather soon then later.

You don't need to finish that today, but if 1.0 is going to be released sometime soon, I could track the master branch temporarily in my project.

**Comment by iwburns** [comment]
I _think_ this is the only blocker, but I'm not super-ultra-_100%_-sure (TM), so I don't want to promise you that.  

The only thing I've been thinking about doing recently is cleaning up some of the documentation examples so that they're a bit more concise and readable.  But that won't be a breaking change, so it's nothing to worry about.

Basically, I'm almost certain that there's nothing left before 1.0 after this, but I don't want to promise you that just in case something comes up.

**Pull request merged**
