### PR TITLE
Implement Debug for Tree and Node

### PR DESCRIPTION
**Pull request by cecton**
Would that helping solving #67 for Debug trait?

It's not super fancy though, here is the output:

> Debug: Tree { id: ProcessUniqueId { prefix: 0, offset: 0 }, root: Some(NodeId { tree_id: ProcessUniqueId { prefix: 0, offset: 0 }, index: 0 }), nodes: [Some(Node { data: 0, parent: None, children: [NodeId { tree_id: ProcessUniqueId { prefix: 0, offset: 0 }, index: 1 }, NodeId { tree_id: ProcessUniqueId { prefix: 0, offset: 0 }, index: 2 }] }), Some(Node { data: 1, parent: Some(NodeId { tree_id: ProcessUniqueId { prefix: 0, offset: 0 }, index: 0 }), children: [NodeId { tree_id: ProcessUniqueId { prefix: 0, offset: 0 }, index: 3 }, NodeId { tree_id: ProcessUniqueId { prefix: 0, offset: 0 }, index: 4 }] }), Some(Node { data: 2, parent: Some(NodeId { tree_id: ProcessUniqueId { prefix: 0, offset: 0 }, index: 0 }), children: [] }), Some(Node { data: 3, parent: Some(NodeId { tree_id: ProcessUniqueId { prefix: 0, offset: 0 }, index: 1 }), children: [] }), Some(Node { data: 4, parent: Some(NodeId { tree_id: ProcessUniqueId { prefix: 0, offset: 0 }, index: 1 }), children: [] })], free_ids: [] }

### CODE REVIEW

**Comment by iwburns** [comment]
Thanks for the PR!

Sadly travis didn't like the build and it looks like it's `rustfmt` related.  It likely has nothing to do with your code, but I can't quite look into it at the moment.  I'll have to come back to this when I get some free time (hopefully within the next few days).

Feel free to mess around with `rustfmt` on your machine and see what it's complaining about, but I don't want you to feel obligated to do so if you don't want to.

**Comment by cecton** [comment]
I've fixed it on #69

**Comment by cecton** [comment]
Now you need to merge this one and we will have Debug for Tree and Node.

**Comment by iwburns** [comment]
Absolutely.  Sorry for the delay here.  I got pulled away.  I should be able to get to this tonight.

**Comment by cecton** [comment]
It's not for me actually it's for #67 😁 I don't have use of id_tree atm

**Comment by iwburns** [comment]
Ha!  Understood.  I'll wait on all of that to get resolved before publishing then.

**Pull request merged**
