### PR TITLE
Implement Clone trait for iterators

### PR DESCRIPTION
**Pull request by ixjf**

### CODE REVIEW

**Comment by ixjf** [comment]
I think this might not actually work as-is. It turns out that the implementation of the Clone trait requires that the type parameters be Clone, rather than the fields, such that cloning e.g. AncestorIds<'a, T> requires that T implements Clone, even though the iterator only holds a reference to some data of type T.

**Comment by ixjf** [comment]
@iwburns Could you please look into this? I need these changes in order to publish my library on crates.io

**Comment by iwburns** [comment]
@ixjf I'm so sorry it has taken me so long to get back to this.

These changes look great to me, however coveralls is failing this change because test coverage went down.

Do you mind writing tests for these new `clone` implementations?  They don't have to be super complicated, I just want to see that a cloned iterator produces the same values as the original one does.

**Comment by ixjf** [comment]
Yes, I should have done that sooner.

**Comment by ixjf** [comment]
Are tests "supposed" to be failing on beta/nightly builds?

**Comment by iwburns** [comment]
This looks great, thanks for adding those for me!  I'll be publishing this shortly and I'll let you know when it's up there.

>Are tests "supposed" to be failing on beta/nightly builds?

In general I don't want them to of course, but I normally try to check the beta/nightly failures to make sure whatever is causing it isn't something I need to be worried about.  In my experience (with this library at least) I've found that it's usually a `rustfmt` rule tweak that causes those breakages, so I don't worry to much about them.  It's annoying, but whenever those tweaks hit stable I just end up running a formatting pass and pushing it to master.

**Comment by iwburns** [comment]
@ixjf I've just pushed up v1.5.0 and it should now be available on crates.io

**Comment by ixjf** [comment]
Great! Thanks!

**Pull request merged**
