### PR TITLE
Update rustfmt

### PR DESCRIPTION
**Pull request by cecton**
1. --write-mode has been replaced by --emit and --check
2. reformat

### CODE REVIEW

**Comment by cecton** [comment]
It still shows the diff if the format is not good and it prevents the build to continue.

**Comment by iwburns** [comment]
Thank you so much for doing this!

My only question is why the change to allowing failures on beta?  I'm not necessarily against allowing beta failures, but I'm curious about your reasoning for making that change.

**Comment by iwburns** [comment]
Also, please feel free to add your name to the list of contributors on the README if you'd like!

**Comment by cecton** [comment]
The format with rustfmt vary from one version to the other. In beta the format is also a bit different than stable and you can make your code match only one format.

**Comment by cecton** [comment]
I thought that's why you allowed failure in nightly?

**Comment by iwburns** [comment]
>The format with rustfmt vary from one version to the other
I was wondering if it was this, but wasn't sure.

>I thought that's why you allowed failure in nightly?
It probably is, it's just been a while since the beta rustfmt had given me an error, so I probably (in error) assumed that beta and stable would use the same rules.

This looks good to me!  Do you want me to wait until you add your name to the contributors list or go ahead and merge?

**Comment by cecton** [comment]
I'm surprised I didn't do it last time. Thanks for reminding me :) I'm glad to have my name on cool open source projects 😁

**Pull request merged**
