### PR TITLE
Enums for method behaviors

### PR DESCRIPTION
**Pull request by iwburns**
This technically works, but there is a lot of cleanup (tests/docs, etc.) that needs to be done.

### CODE REVIEW

**Comment by Drakulix** [comment]
Looks good to me, except for the TODOs you listed yourself.

**Comment by iwburns** [comment]
Alright, apart from the conflict (I'll take care of that right before I do the merge), do you see anything missing?  Anything that you think should be tweaked?

I'm not in love with the name `RemoveBehavior` but I can't think of anything much better than that either.

Ping @Drakulix

**Comment by Drakulix** [comment]
I am not entirely happy with the examples gone, although we don't need that many that complex examples anymore. But maybe add some very short ones to the enum variants?

Otherwise this is done.

**Comment by iwburns** [comment]
I agree, I'll get on that once I've got some free time over the holiday.

Thanks for taking a look!

**Comment by iwburns** [comment]
@Drakulix alright I've added the docs tests, (again, apart from the conflict) do you see anything that needs addressing here?

**Comment by Drakulix** [comment]
> do you see anything that needs addressing here?

Nope. Looks good!

**Pull request merged**
