### PR TITLE
Update README example with new iterators

### LINKED ISSUE #42: Update README
Just noticed now that #41 is merged, the example in the README should most likely be updated.

### PR DESCRIPTION
**Pull request by iwburns**
fixes #42

### CODE REVIEW

**Comment by iwburns** [comment]
@Drakulix haha! I appreciate the heads up, I was right in the middle of doing that when you submitted the issue.

**Comment by Drakulix** [comment]
My first thought was "WOW, that was quick!"

**Comment by iwburns** [comment]
Hmmmm, not sure what is going on here, `cargo fmt` is behaving differently on travis all of a sudden...

**Comment by iwburns** [comment]
I think a new version of rustfmt literally was just released or something.  So I'm grabbing it and re-testing locally now.

**Pull request merged**
