### PR TITLE
add write_formatted method

### PR DESCRIPTION
**Pull request by spearman**
This is basically the same routine as in `slab_tree`, outputting a formatted string representation of the tree that resembles the linux `tree` command.

### CODE REVIEW

**Comment by iwburns** [comment]
This looks good, Travis failed the build for some reason, not sure why.  I triggered another build and we'll see where it goes.  I might have to run `cargo fmt` on the whole lib again to get it cleaned up again (tends to happen to me whenever a new version of rustfmt comes out).

**Comment by iwburns** [comment]
Looks like I did have to update the travis config (last time I ran this, cargo fmt was just in "preview" stage) and re-run `cargo fmt` on the library.

Do you mind merging master back in and re-running cargo fmt (if necessary)?

**Comment by spearman** [comment]
Merged, looks like that took care of cargo fmt

**Comment by iwburns** [comment]
thanks!

**Pull request merged**
