### PR TITLE
bug-invalid_tree_root

### PR DESCRIPTION
**Pull request by iwburns**
@Drakulix I've started on this, but may not be able to finish it tonight, feel free to take a look, but this is obviously still in-progress.

### CODE REVIEW

**Comment by iwburns** [comment]
@Drakulix I'd like your input on this one (if you don't mind).

I think it's technically done, but the code needs to be cleaned up a bit for sure.  I won't be able to clean it up until tomorrow morning though.

**Comment by iwburns** [comment]
pinging @Drakulix 
Alright, I've cleaned it up a bit now.  There is still a little bit of code repetition, but I think it is more readable the way it is.

Let me know your thoughts on this if you have time.  I would especially appreciate it if you looked at the tests that I've added.  I think I covered all of the cases, but a second set of eyes on that would help very much.

**Comment by Drakulix** [comment]
Sorry for the late reply. I am quite busy this weekend, but be sure I will happily read through all of this at monday.

**Comment by iwburns** [comment]
No problem at all :) take your time!

**Comment by iwburns** [comment]
Alright, I'm done with this one.

The only thing that remains is to resolve the discussion in #11 because there is a question in there about this method's behavior in one specific scenario (moving down the tree when there is more than one `Node` directly between the `Node` being moved and its new "target parent").

Whatever the outcome on that though, it shouldn't be too hard to adjust the current behavior if needed.

**Comment by Drakulix** [comment]
I am hugely in favor of your current solution. The second one also makes sense, but it moves to much around. I would claim the solution doing the least modifications to the overall structure of the whole tree is the best.

Disconnecting the trees is far to difficult to express through the API and also certainly not expected.

Code-wise is looks very good, especially the extensive testing is very nice to see. I have not found any errors in this implementation and in the tests, which make me very confident in that statement.

**Comment by iwburns** [comment]
@Drakulix I agree. Less shifting seems more logical.  My only concern now is coming up with the proper wording to describe this behavior very precisely so that it is very clear what this function does.

I almost want to make a small drawing in the docs, but that seems like it's not appropriate.  I'll see if I can come up with some wording that is clear and we can just include a small (ascii-art) drawing as a last resort.

Thanks so much for reviewing this!  I know you said you've been busy and haven't had time lately, but this is very much appreciated!

By the way, feel free to add yourself (name, github link, or whatever you want) to the Contributors section of the Readme in one of your PRs.  You've helped me out very much on this project so far and I would love to recognize you for it (it's totally up to you of course).

**Comment by iwburns** [comment]
Fixes #11 
@Drakulix I've updated the documentation for that method.  Please let me know if you think that wording is clear enough to convey the proper message.

**Comment by Drakulix** [comment]
The only slightly problematic part is 
```
... the direct child of `A` that is between it and `B` ...
```

This might be confusing, if B is the direct child itself.
What about:
```
.. the first child of `A` on the path from `A` to `B` ...
```

Also I do not think including an additional drawing is a bad idea, even if the wording is clear.
Graphic representations of tree's are always easier to grasp and the same markdown code we use here should work just fine in rustdoc as well.

**Comment by iwburns** [comment]
I like that wording much better. I've made the change.

Also, I tried to include an ascii-art drawing of the tree, but I couldn't get it to render properly.  I think there might be a bug with the behavior listed [here](https://doc.rust-lang.org/book/documentation.html#code-block-annotations) because using ` ```text ` didn't help at all.  In any case, that can be update later if need be.

**Comment by Drakulix** [comment]
Nope, no other issues.

I will try to update #6 in the next days once this is merged.

**Comment by iwburns** [comment]
v0.2.8 has been pushed up to crates.io

**Pull request merged**
