### PR TITLE
Implementation of move_node_to_root

### LINKED ISSUE #20: How to set root from orphan node
This is basically the last topic from #7 .
@iwburns , you said `remove_node_lift_children` is not supposed to set the root node, even if only one child remaining.
Given that case, there is no way to manually set that child as the new root, without removing it at first.

My current workaround:
```
let new_root_id = self.tree.get(&old_root_id).unwrap().children()[0].clone();

let children = self.tree.get(&new_root_id).unwrap().children().clone();

let new_root = self.tree.remove_node_orphan_children(new_root_id.clone()).unwrap();
self.tree.remove_node_drop_children(old_root_id).unwrap();
self.tree.set_root(new_root);

for child in children
{
    self.tree.move_node_to_parent(&child, &new_root_id);
}
```

This is hideous.

### PR DESCRIPTION
**Pull request by Drakulix**
Fixes #20 

I don't have time for much more today, but I wanted some initial feedback.
Is it really that easy? @iwburns 

Feel free to finish this yourself, if you want to. Otherwise I will do later.

### CODE REVIEW

**Comment by iwburns** [comment]
I _think_ that's all you need, but I'll do a more thorough investigation tonight when I get back to the house.

**Comment by iwburns** [comment]
Alright, I've done some more investigation here.  There are several cases to consider:
- if the `Tree` has a root, we can just call `move_node_to_parent(&current_root, &new_root)`.  There's no need to worry about setting parent/child/root values "manually" because that's already taken care of in `move_node_to_parent` (you can find that behavior [here](https://github.com/iwburns/id-tree/blob/master/src/tree.rs#L498)).
- if the `Tree` doesn't have a root, we need to manually detach from parent (which at this point, I feel like we need a private function for this because we do it so much) and then set parent to None and of course set the tree root to the new `NodeId`.

Does that sound right to you?  I had to draw it out on paper, but I think that catches all edge cases here.

ping @Drakulix

**Comment by Drakulix** [comment]
> if the Tree has a root, we can just call move_node_to_parent(&current_root, &new_root). There's no need to worry about setting parent/child/root values "manually" because that's already taken care of in move_node_to_parent (you can find that behavior here).

Right thats even easier. Didn't remember that `move_node_to_parent` already handles the edge-case of moving the root-node that easily.

> if the Tree doesn't have a root, we need to manually detach from parent (which at this point, I feel like we need a private function for this because we do it so much) and then set parent to None and of course set the tree root to the new NodeId.

The case of clearing out the parent of the moved node is obviously missing from my implementation, because I thought only about already orphan nodes. I will fix that.

> Does that sound right to you? I had to draw it out on paper, but I think that catches all edge cases here.

Yes. I took some time to think about this and this seems about right.
I will finish this, once I got the time.

**Comment by iwburns** [comment]
Awesome, and no rush, I totally understand if you're busy (especially during the holiday season), I know I am as well. :)

**Comment by Drakulix** [comment]
> if the Tree has a root, we can just call move_node_to_parent(&current_root, &new_root). There's no need to worry about setting parent/child/root values "manually" because that's already taken care of in move_node_to_parent (you can find that behavior here).

This actually did not work, if the child moved to the root of the tree is further down the tree, then the first layer. With the given implementation of `move_node_to_parent` this happens:
```
A
|
B
|
C

move_node_to_root(C) != move_node_to_parent(A, C):

B
|
C
|
A

Expected:

C
|
A
|
B
```

This implementation works now. I have added documentation and a bunch of tests.
No rush with merging or reviewing this in the holidays. I just wanted to get this out.

**Comment by Drakulix** [comment]
Update:
And I actually added a new private function, just like you asked. And made sure clear_parent gets used more often. Maybe that should be done for all private functions.

**Comment by iwburns** [comment]
>And I actually added a new private function, just like you asked. And made sure clear_parent gets used more often.

Thanks!

>Maybe that should be done for all private functions.

Yeah, I've been meaning to do this.  In fact, I'm thinking about proposing a moderately large re-factor to see what your thoughts are.  It might make it easier to write iterators as we discussed in #23.

In any case, I'm thinking this PR looks good from my end.  Any more thoughts before I merge?

ping @Drakulix (no rush)

**Comment by Drakulix** [comment]
Nope. I consider this finished.

**Comment by iwburns** [comment]
@Drakulix this is up on crates.io

**Pull request merged**
